### PR TITLE
feat: add kubernetes service registration

### PR DESCRIPTION
**Pull request by bchrobot**
See: https://www.vaultproject.io/docs/configuration/service-registration/kubernetes

And https://github.com/hashicorp/vault/pull/9073 for why `"patch"` verb is included.

### CODE REVIEW

**Comment by sethvargo** [comment]
Thanks!

**Comment by agates4** [comment]
@bchrobot check out issue #95 , looks like this PR broke some firewall networking (not sure exactly what happened).
after reverting the changes this PR made, the terraform apply worked as expected.

note: I am using an existing project rather than having terraform create a new one.

**Comment by agates4** [comment]
looks like the result is, using the standard flow described in the README with the latest code changes, the public IP listed does _not_ navigate to the vault UI, and instead hangs - and as far as the API, that too will hang.

**Comment by agates4** [comment]
@sethvargo re: #95

**Pull request merged**
